### ISSUE TITLE
Numerous anomalies when uploading tracks, failing upload for large tracks

### ISSUE THREAD

**Issue by ghost** [mapilio/mapilio-kit-v2#188]
Short Information 
* Used Device: HP 17-cn2283st
* Used Toolkit version: 3.0.1
* Operating System:  Windows

### Problem Definition Briefly (might be explained in steps)
* When uploading large tracks it throws an error message without any uploading

### Expected Output
* Upload tracks without anomalies

### Actual Output
Welcome to Mapilio-kit
Mapilio allows you to upload your images, videos and 360 degree panorama images to Mapilio map.
A newer version (3.0.1) is available!
For latest Mapilio-kit version please update with "pip install mapilio_kit --upgrade"

{
"total_images": 64,
"processed_images": 61,
"failed_images": 3,
"duplicated_images": 0,
"id": "8323ff0a01fe49d1b55e610279f62828",
"device_type": "Desktop",
"anomaly_sequences": []
}
Anomalies can occur due to a combination of factors, including GPS distance being out of range,heading angle limit being exceeded, and altitude surpassing the upper limit. This contributes to the existence of failed images.
Some images has failed to upload due to anomaly detection. These images are => ['1308311_0_59699_51.jpg', '1308311_0_59699_51.jpg', '1308311_0_59699_58.jpg']
If shooting was taken at a point outside the polygon, these points and images will be published publicly...

### Extra information (can contain screen shots)
![error2](https://github.com/user-attachments/assets/310871c8-594b-403d-83c8-5d650777bbc8)

**Comment by Zh9567** [comment]
Hi there, I think this need to be reopen and needs moderator's attention, as I have the same issue too. None of my tracks were uploaded successfully into Mapilio.
